In [ ]:
### Yiğit Şevki KAPLAN
### 22243810049
### 22.10.2025
### Logistic Regression

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import numpy as np
# libraries imported

In [ ]:
studentperf = pd.read_csv("Student_Performance_binary.csv")

In [ ]:
studentperf.head()

,Unnamed: 0,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,0,7,99,Yes,9,1,1
1,1,4,82,No,4,2,1
2,2,8,51,Yes,7,2,0
3,3,5,52,Yes,5,2,0
4,4,7,75,No,8,5,1

In [ ]:
# Performance index binary, Kaldı | Geçti

In [ ]:
studentperf.drop(studentperf.columns[0], axis = 1, inplace = True)

In [ ]:
# 1. satırı veriden çıkartıyoruz. Saymaya 0 dan başlandığı için studentperf.columns[0] yazdık.

In [ ]:
studentperf.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,1
1,4,82,No,4,2,1
2,8,51,Yes,7,2,0
3,5,52,Yes,5,2,0
4,7,75,No,8,5,1

In [ ]:
Y = studentperf['Performance Index']
X = studentperf.drop('Performance Index', axis = 1)

In [ ]:
X.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,Yes,9,1
1,4,82,No,4,2
2,8,51,Yes,7,2
3,5,52,Yes,5,2
4,7,75,No,8,5

In [ ]:
# Extracurricular Activities, Yes:1 No:0 yapacağız

In [ ]:
X['Extracurricular Activities'] = X['Extracurricular Activities'].replace({'No':0, 'Yes': 1})

/tmp/ipython-input-2983069802.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X['Extracurricular Activities'] = X['Extracurricular Activities'].replace({'No':0, 'Yes': 1})

In [ ]:
X.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,1,9,1
1,4,82,0,4,2
2,8,51,1,7,2
3,5,52,1,5,2
4,7,75,0,8,5

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, train_size=0.8, random_state = 42)

In [ ]:
x_train_sm = sm.add_constant(x_train)

In [ ]:
logml = sm.Logit(y_train, x_train_sm).fit()

Optimization terminated successfully.
         Current function value: 0.058186
         Iterations 12

In [ ]:
print(logml.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:      Performance Index   No. Observations:                 8000
Model:                          Logit   Df Residuals:                     7994
Method:                           MLE   Df Model:                            5
Date:                Tue, 02 Dec 2025   Pseudo R-squ.:                  0.9149
Time:                        14:28:56   Log-Likelihood:                -465.49
converged:                       True   LL-Null:                       -5469.0
Covariance Type:            nonrobust   LLR p-value:                     0.000
====================================================================================================
                                       coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------------
const                              -85.6085      3.954    -21.653      0.000     -93.358     -77.859
Hours Studied                        2.6254      0.126     20.872      0.000       2.379       2.872
Previous Scores                      0.9293      0.043     21.781      0.000       0.846       1.013
Extracurricular Activities           0.9008      0.174      5.183      0.000       0.560       1.241
Sleep Hours                          0.4185      0.052      8.086      0.000       0.317       0.520
Sample Question Papers Practiced     0.1971      0.031      6.396      0.000       0.137       0.258
====================================================================================================

Possibly complete quasi-separation: A fraction 0.67 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.

In [ ]:
# logaritmik olarak değişiklerini veriyor

In [ ]:
print(np.exp(logml.params))

const                               6.617632e-38
Hours Studied                       1.381018e+01
Previous Scores                     2.532661e+00
Extracurricular Activities          2.461510e+00
Sleep Hours                         1.519687e+00
Sample Question Papers Practiced    1.217873e+00
dtype: float64

In [ ]:
# x lerin odd oranına değişimini veriyor

In [ ]:
print(logml.get_margeff().summary())

        Logit Marginal Effects
=====================================
Dep. Variable:      Performance Index
Method:                          dydx
At:                           overall
====================================================================================================
                                      dy/dx    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------------
Hours Studied                        0.0463      0.001     69.635      0.000       0.045       0.048
Previous Scores                      0.0164   6.27e-05    260.940      0.000       0.016       0.016
Extracurricular Activities           0.0159      0.003      5.354      0.000       0.010       0.022
Sleep Hours                          0.0074      0.001      8.711      0.000       0.006       0.009
Sample Question Papers Practiced     0.0035      0.001      6.702      0.000       0.002       0.004
====================================================================================================

In [ ]:
# dy/dx değişim oranını veriyor, örn. Hours Studied değişkeni bir atrtırılrsa,
#                                       başarılı olma olasılığı 0.0463 artıyor.

In [ ]:
y_hat = logml.predict(x_train_sm)

In [ ]:
y_hat

9254    9.937201e-11
1561    4.465736e-14
1670    1.464115e-01
6087    6.946616e-16
6669    3.517275e-08
            ...
5734    1.307638e-06
5191    5.213234e-04
5390    1.738141e-06
860     3.671233e-16
7270    1.861157e-15
Length: 8000, dtype: float64

In [ ]:
# 1 sınıfında(başarılı) olma olasılıkları

In [ ]:
y_hat_b = (y_hat>0.5).astype(int)

In [ ]:
y_hat_b

9254    0
1561    0
1670    0
6087    0
6669    0
       ..
5734    0
5191    0
5390    0
860     0
7270    0
Length: 8000, dtype: int64

In [ ]:
# 0.5 üstünde kalanlara 1, altında kalanlara 0 dedik

In [ ]:
report = classification_report(y_train,y_hat_b)

In [ ]:
print(report)

              precision    recall  f1-score   support

           0       0.98      0.98      0.98      4551
           1       0.97      0.97      0.97      3449

    accuracy                           0.97      8000
   macro avg       0.97      0.97      0.97      8000
weighted avg       0.97      0.97      0.97      8000

In [ ]:
print(confusion_matrix(y_train,y_hat_b))

[[4442  109]
 [  93 3356]]

In [ ]:
accuracy = (4442+3356)/(4442+3356+109+93)
print(accuracy)

0.97475

In [ ]:
x_test_sm = sm.add_constant(x_test)

In [ ]:
logml_test = sm.Logit(y_test, x_test_sm).fit()

Optimization terminated successfully.
         Current function value: 0.053758
         Iterations 12

In [ ]:
print(logml_test.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:      Performance Index   No. Observations:                 2000
Model:                          Logit   Df Residuals:                     1994
Method:                           MLE   Df Model:                            5
Date:                Tue, 02 Dec 2025   Pseudo R-squ.:                  0.9210
Time:                        14:28:56   Log-Likelihood:                -107.52
converged:                       True   LL-Null:                       -1360.9
Covariance Type:            nonrobust   LLR p-value:                     0.000
====================================================================================================
                                       coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------------
const                              -92.8545      8.858    -10.482      0.000    -110.216     -75.493
Hours Studied                        2.7480      0.270     10.169      0.000       2.218       3.278
Previous Scores                      0.9986      0.094     10.571      0.000       0.813       1.184
Extracurricular Activities           1.1532      0.370      3.118      0.002       0.428       1.878
Sleep Hours                          0.6671      0.128      5.226      0.000       0.417       0.917
Sample Question Papers Practiced     0.1663      0.067      2.481      0.013       0.035       0.298
====================================================================================================

Possibly complete quasi-separation: A fraction 0.70 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.

In [ ]:
print(np.exp(logml_test.params))

const                               4.718702e-41
Hours Studied                       1.561210e+01
Previous Scores                     2.714412e+00
Extracurricular Activities          3.168200e+00
Sleep Hours                         1.948563e+00
Sample Question Papers Practiced    1.180916e+00
dtype: float64

In [ ]:
print(logml_test.get_margeff().summary())

        Logit Marginal Effects
=====================================
Dep. Variable:      Performance Index
Method:                          dydx
At:                           overall
====================================================================================================
                                      dy/dx    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------------
Hours Studied                        0.0445      0.001     34.112      0.000       0.042       0.047
Previous Scores                      0.0162      0.000    105.793      0.000       0.016       0.016
Extracurricular Activities           0.0187      0.006      3.272      0.001       0.007       0.030
Sleep Hours                          0.0108      0.002      5.914      0.000       0.007       0.014
Sample Question Papers Practiced     0.0027      0.001      2.537      0.011       0.001       0.005
====================================================================================================

In [ ]:
y_hat_test = logml_test.predict(x_test_sm)

In [ ]:
y_hat_test_b = (y_hat_test>0.5).astype(int)

In [ ]:
report = classification_report(y_test,y_hat_test_b)

In [ ]:
print(report)

              precision    recall  f1-score   support

           0       0.98      0.98      0.98      1159
           1       0.97      0.97      0.97       841

    accuracy                           0.98      2000
   macro avg       0.97      0.97      0.97      2000
weighted avg       0.98      0.98      0.98      2000

In [ ]:
# train testi için uyguladığımız işlemleri, test seti içinde uyguladık.

### TERT SETİ İÇİNDE AYNI PREDICT MODELİNİ KULLAN

In [ ]:
y_hat_t_test = logml.predict(x_test_sm)

In [ ]:
y_hat_t_test_b = (y_hat_t_test>0.5).astype(int)

In [ ]:
report = classification_report(y_test, y_hat_t_test_b)

In [ ]:
print(report)

              precision    recall  f1-score   support

           0       0.98      0.98      0.98      1159
           1       0.97      0.97      0.97       841

    accuracy                           0.98      2000
   macro avg       0.98      0.98      0.98      2000
weighted avg       0.98      0.98      0.98      2000