In [ ]:
### Yiğit Şevki Kaplan
### 22243810049
### 26.11.2025
### SVM

In [ ]:
import pandas as pd
from sklearn import datasets

In [ ]:
# hazır datasetler

In [ ]:
cancer = datasets.load_breast_cancer()

In [ ]:
print(cancer.feature_names)

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']

In [ ]:
# features = x'ler

In [ ]:
print(cancer.target_names)

['malignant' 'benign']

In [ ]:
#targer = y'ler

In [ ]:
df = pd.DataFrame(cancer.data, columns = cancer.feature_names)

In [ ]:
df.head()

   mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [ ]:
df['target'] = cancer.target

In [ ]:
df.head()

   mean radius  mean texture  ...  worst fractal dimension  target
0        17.99         10.38  ...                  0.11890       0
1        20.57         17.77  ...                  0.08902       0
2        19.69         21.25  ...                  0.08758       0
3        11.42         20.38  ...                  0.17300       0
4        20.29         14.34  ...                  0.07678       0

[5 rows x 31 columns]

In [ ]:
# ['malignant' = 0, 'benign' = 1] olarak, target columunun altına ekleniyor

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
target                     0
dtype: int64

In [ ]:
# no null values

In [ ]:
df['target'].value_counts()

target
1    357
0    212
Name: count, dtype: int64

In [ ]:
# 212 malignant, 357 benign

In [ ]:
sns.pairplot(df,hue='target', palette=['red','green'])

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
# our goal is to seperate red and green values

In [ ]:
X = df.drop(['target'], axis = 1)
Y = df['target']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, train_size = 0.8, stratify = Y,random_state = 149)

In [ ]:
svc = svm.SVC()

In [ ]:
svc.fit(x_train,y_train)

SVC()

In [ ]:
df['target'].value_counts()/len(df)

target
1    0.627417
0    0.372583
Name: count, dtype: float64

In [ ]:
# If its keep guessing 1, its accuracy would be 63%. Our algorithm needs to get better score than 63%

In [ ]:
y_pred = svc.predict(x_test)

In [ ]:
accuracy_score(y_test, y_pred)

0.868421052631579

In [ ]:
# Our score for the "kernel = radial basis, c = 1" is 87%, its better than 63%. Acceptable

In [ ]:
svc_c10 = svm.SVC(C=10)

In [ ]:
# kernel = radial basis, c = 10

In [ ]:
svc_c10.fit(x_train, y_train)

SVC(C=10)

In [ ]:
y_predc10 = svc_c10.predict(x_test)

In [ ]:
accuracy_score(y_test, y_predc10)

0.8771929824561403

In [ ]:
# its better than, radial basis, c = 1. Thus when c is larger than 1 to the some point it would give better accuracy.

In [ ]:
svc_c10_lin = svm.SVC(kernel = 'linear', C=10)

In [ ]:
svc_c10_lin.fit(x_train,y_train)

SVC(C=10, kernel='linear')

In [ ]:
y_predc10lin = svc_c10_lin.predict(x_test)

In [ ]:
accuracy_score(y_test, y_predc10lin)

0.9473684210526315

In [ ]:
# its better than radial, c = 10. Thus kernel = liner better algorithm than radial in our case.

In [ ]:
svc_c10_sig = svm.SVC(kernel='sigmoid', C=10)

In [ ]:
svc_c10_sig.fit(x_train,y_train)

SVC(C=10, kernel='sigmoid')

In [ ]:
y_predc10sig = svc_c10_sig.predict(x_test)

In [ ]:
accuracy_score(y_test, y_predc10sig)

0.4298245614035088

In [ ]:
# kernel = sigmoid worse than linear, linear kernel still optimal

In [ ]:
svc_c10_poly = svm.SVC(kernel = 'poly', C=10)

In [ ]:
svc_c10_poly.fit(x_train, y_train)

SVC(C=10, kernel='poly')

In [ ]:
y_predc10poly = svc_c10_poly.predict(x_test)

In [ ]:
accuracy_score(y_test, y_predc10poly)

0.868421052631579

In [ ]:
# our algorithms kernels: linear>radial>poly>sigmoid, C when bigger than 1 we get a more accurate results.
# highest accuracy out of all our tries : kernel = 'linear', C=10 with 0.947 accuracy