In [188]:
# Save this colab notebook as name_surname
# You should upload this notebook to the moodle page of the course IE411 as classwork 4
# This is a 10 point classwork

In [189]:
# Name: Yiğit Şevki
# Surname: Kaplan
# Student ID: 22243810049
# Classwork 4

In [190]:
# 1)
# Import the following libraries
# Pandas,seaborn,statsmodels.api

In [191]:
import pandas as pd
import seaborn as sns
import statsmodels.api as sm

In [192]:
# 2) Import classification_report, confusion_matrix,accuracy_score functions from sklearn.metrics library
#    Import train_test_split from sklearn.model_selection

In [193]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split

In [194]:
# 3 ) Read the dataset called "hear_disease.csv" and call it "hd"

In [195]:
hd = pd.read_csv('Heart_disease.csv')

In [196]:
# 4) Write the first 10 observations of hd

In [197]:
hd.head(10)

   male  age  education  currentSmoker  ...    BMI  heartRate  glucose  TenYearCHD
0     1   39        4.0              0  ...  26.97       80.0     77.0           0
1     0   46        2.0              0  ...  28.73       95.0     76.0           0
2     1   48        1.0              1  ...  25.34       75.0     70.0           0
3     0   61        3.0              1  ...  28.58       65.0    103.0           1
4     0   46        3.0              1  ...  23.10       85.0     85.0           0
5     0   43        2.0              0  ...  30.30       77.0     99.0           0
6     0   63        1.0              0  ...  33.11       60.0     85.0           1
7     0   45        2.0              1  ...  21.68       79.0     78.0           0
8     1   52        1.0              0  ...  26.36       76.0     79.0           0
9     1   43        1.0              1  ...  23.61       93.0     88.0           0

[10 rows x 16 columns]

In [198]:
'''
Please read the explanation about the dataset very carefully

Variables
Each attribute is a potential risk factor. There are both demographic, behavioral and medical risk factors.

Demographic:
• Sex: male or female(Nominal)
• Age: Age of the patient;(Continuous - Although the recorded ages have been truncated to whole numbers, the concept of age is continuous)


Behavioral:
• Current Smoker: whether or not the patient is a current smoker (Nominal)
• Cigs Per Day: the number of cigarettes that the person smoked on average in one day.(can be considered continuous as one can have any number of cigarettes, even half a cigarette.)
Medical( history)

• BP Meds: whether or not the patient was on blood pressure medication (Nominal)
• Prevalent Stroke: whether or not the patient had previously had a stroke (Nominal)
• Prevalent Hyp: whether or not the patient was hypertensive (Nominal)
• Diabetes: whether or not the patient had diabetes (Nominal)
Medical(current)

• Tot Chol: total cholesterol level (Continuous)
• Sys BP: systolic blood pressure (Continuous)
• Dia BP: diastolic blood pressure (Continuous)
• BMI: Body Mass Index (Continuous)
• Heart Rate: heart rate (Continuous - In medical research, variables such as heart rate though in fact discrete, yet are considered continuous because of large number of possible values.)
• Glucose: glucose level (Continuous)

*** Predict variable (desired target) ***

• 10 year risk of coronary heart disease CHD (binary: “1”, means “Yes”, “0” means “No”)'

'''

" \nPlease read the explanation about the dataset very carefully\n\nVariables\nEach attribute is a potential risk factor. There are both demographic, behavioral and medical risk factors.\n\nDemographic:\n• Sex: male or female(Nominal)\n• Age: Age of the patient;(Continuous - Although the recorded ages have been truncated to whole numbers, the concept of age is continuous)\n\n\nBehavioral:\n• Current Smoker: whether or not the patient is a current smoker (Nominal)\n• Cigs Per Day: the number of cigarettes that the person smoked on average in one day.(can be considered continuous as one can have any number of cigarettes, even half a cigarette.)\nMedical( history)\n\n• BP Meds: whether or not the patient was on blood pressure medication (Nominal)\n• Prevalent Stroke: whether or not the patient had previously had a stroke (Nominal)\n• Prevalent Hyp: whether or not the patient was hypertensive (Nominal)\n• Diabetes: whether or not the patient had diabetes (Nominal)\nMedical(current)\n\n• Tot Chol: total cholesterol level (Continuous)\n• Sys BP: systolic blood pressure (Continuous)\n• Dia BP: diastolic blood pressure (Continuous)\n• BMI: Body Mass Index (Continuous)\n• Heart Rate: heart rate (Continuous - In medical research, variables such as heart rate though in fact discrete, yet are considered continuous because of large number of possible values.)\n• Glucose: glucose level (Continuous)\n\n*** Predict variable (desired target) ***\n\n• 10 year risk of coronary heart disease CHD (binary: “1”, means “Yes”, “0” means “No”)'\n\n"

In [199]:
# 5) Find the number of variables and observations

In [200]:
hd.shape

(4238, 16)

In [201]:
# 16 variables, 4238 observations

In [202]:
# 6) Write the variables which are type int64

In [203]:
hd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238 entries, 0 to 4237
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   male             4238 non-null   int64
 1   age              4238 non-null   int64
 2   education        4133 non-null   float64
 3   currentSmoker    4238 non-null   int64
 4   cigsPerDay       4209 non-null   float64
 5   BPMeds           4185 non-null   float64
 6   prevalentStroke  4238 non-null   int64
 7   prevalentHyp     4238 non-null   int64
 8   diabetes         4238 non-null   int64
 9   totChol          4188 non-null   float64
 10  sysBP            4238 non-null   float64
 11  diaBP            4238 non-null   float64
 12  BMI              4219 non-null   float64
 13  heartRate        4237 non-null   float64
 14  glucose          3850 non-null   float64
 15  TenYearCHD       4238 non-null   int64
dtypes: float64(9), int64(7)
memory usage: 529.9 KB

In [204]:
# X(independent):   male, age, currentSmoker, prevalentStroke, prevalentHyp, diabetes
# Y(dependent):     TenYearCHD

In [205]:
# 7) Write the variables which have missing variables

In [206]:
hd.isnull().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [207]:
# education(105), cigsPerDay(29), BPMeds(53), totChol(50), BMI(19), heartRate(1), glucose(388)

In [208]:
# 8) Use the following codes to write number of missing observations for each variable
# hd.isna().sum()

In [209]:
hd.isna().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [210]:
# education(105), cigsPerDay(29), BPMeds(53), totChol(50), BMI(19), heartRate(1), glucose(388)

In [211]:
# 9) Which variable has the highest number of missing observations

In [212]:
# glucose(388)

In [213]:
# 10) Use the following codes to fill missing values of each variable with the mean of that variable

# hd['education'] = hd['education'].fillna(hd['education'].mean())
# hd['cigsPerDay'] = hd['cigsPerDay'].fillna(hd['cigsPerDay'].mean())
# hd['BPMeds'] = hd['BPMeds'].fillna(hd['BPMeds'].mean())
# hd['totChol'] = hd['totChol'].fillna(hd['totChol'].mean())
# hd['BMI'] = hd['BMI'].fillna(hd['BMI'].mean())
# hd['heartRate'] = hd['heartRate'].fillna(hd['heartRate'].mean())
# hd['glucose'] = hd['glucose'].fillna(hd['glucose'].mean())

In [214]:
hd['education'] = hd['education'].fillna(hd['education'].mean())
hd['cigsPerDay'] = hd['cigsPerDay'].fillna(hd['cigsPerDay'].mean())
hd['BPMeds'] = hd['BPMeds'].fillna(hd['BPMeds'].mean())
hd['totChol'] = hd['totChol'].fillna(hd['totChol'].mean())
hd['BMI'] = hd['BMI'].fillna(hd['BMI'].mean())
hd['heartRate'] = hd['heartRate'].fillna(hd['heartRate'].mean())
hd['glucose'] = hd['glucose'].fillna(hd['glucose'].mean())

In [215]:
# 11) Write number of missing observations for each variable

In [216]:
hd.isnull().sum()

male               0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [217]:
# 12) Define TenYearCHD as your y variable, the rest will be your X variables

In [218]:
X = hd.drop(['TenYearCHD'], axis = 1)
Y = hd['TenYearCHD']

In [219]:
# 13) Write the first 5 observations of y and X to chek if they are correctly defined

In [220]:
X.head()

   male  age  education  currentSmoker  ...  diaBP    BMI  heartRate  glucose
0     1   39        4.0              0  ...   70.0  26.97       80.0     77.0
1     0   46        2.0              0  ...   81.0  28.73       95.0     76.0
2     1   48        1.0              1  ...   80.0  25.34       75.0     70.0
3     0   61        3.0              1  ...   95.0  28.58       65.0    103.0
4     0   46        3.0              1  ...   84.0  23.10       85.0     85.0

[5 rows x 15 columns]

In [221]:
Y.head()

0    0
1    0
2    0
3    1
4    0
Name: TenYearCHD, dtype: int64

In [222]:
# 14) Divide your data set into test and train sets. Test set should contain %30 of the data set. Use random state as 123

In [223]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 123)

In [224]:
# 15) Add constant to X_train and call it X_train_c

In [225]:
x_train_c = sm.add_constant(x_train)

In [226]:
# 16) Fit the logistic regression and call it loglr

In [227]:
loglr = sm.Logit(y_train, x_train_c).fit()

Optimization terminated successfully.
         Current function value: 0.370428
         Iterations 7

In [228]:
#17) Print the summary of the logistic regression

In [229]:
print(loglr.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:             TenYearCHD   No. Observations:                 2966
Model:                          Logit   Df Residuals:                     2950
Method:                           MLE   Df Model:                           15
Date:                Wed, 03 Dec 2025   Pseudo R-squ.:                  0.1114
Time:                        07:46:37   Log-Likelihood:                -1098.7
converged:                       True   LL-Null:                       -1236.5
Covariance Type:            nonrobust   LLR p-value:                 6.650e-50
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              -8.0620      0.815     -9.888      0.000      -9.660      -6.464
male                0.4887      0.122      4.008      0.000       0.250       0.728
age                 0.0659      0.008      8.692      0.000       0.051       0.081
education          -0.0293      0.057     -0.516      0.606      -0.141       0.082
currentSmoker      -0.0857      0.172     -0.499      0.618      -0.423       0.251
cigsPerDay          0.0266      0.007      4.015      0.000       0.014       0.040
BPMeds              0.1720      0.261      0.659      0.510      -0.339       0.683
prevalentStroke     1.4071      0.555      2.537      0.011       0.320       2.494
prevalentHyp        0.2439      0.155      1.573      0.116      -0.060       0.548
diabetes            0.3016      0.369      0.817      0.414      -0.422       1.025
totChol             0.0013      0.001      1.023      0.307      -0.001       0.004
sysBP               0.0105      0.004      2.440      0.015       0.002       0.019
diaBP               0.0005      0.007      0.062      0.951      -0.014       0.015
BMI                -0.0008      0.014     -0.055      0.956      -0.029       0.027
heartRate          -0.0006      0.005     -0.134      0.894      -0.010       0.009
glucose             0.0080      0.003      2.924      0.003       0.003       0.013
===================================================================================

In [230]:
#18) Write which coefficients are statistically non-significant

In [231]:
# education, currentSmoker, BPMeds, prevalentHyp, diabetes, totChol, diaBP, BMI, heartRate

In [232]:
#19) Get marginal effects of the fitted model and comment on which variable has the highest effects on Y.

In [233]:
print(loglr.get_margeff().summary())

        Logit Marginal Effects
=====================================
Dep. Variable:             TenYearCHD
Method:                          dydx
At:                           overall
===================================================================================
                     dy/dx    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
male                0.0548      0.014      4.019      0.000       0.028       0.082
age                 0.0074      0.001      8.806      0.000       0.006       0.009
education          -0.0033      0.006     -0.516      0.606      -0.016       0.009
currentSmoker      -0.0096      0.019     -0.499      0.618      -0.047       0.028
cigsPerDay          0.0030      0.001      4.032      0.000       0.002       0.004
BPMeds              0.0193      0.029      0.659      0.510      -0.038       0.077
prevalentStroke     0.1578      0.062      2.547      0.011       0.036       0.279
prevalentHyp        0.0273      0.017      1.573      0.116      -0.007       0.061
diabetes            0.0338      0.041      0.817      0.414      -0.047       0.115
totChol             0.0001      0.000      1.022      0.307      -0.000       0.000
sysBP               0.0012      0.000      2.447      0.014       0.000       0.002
diaBP            5.172e-05      0.001      0.062      0.951      -0.002       0.002
BMI             -8.759e-05      0.002     -0.055      0.956      -0.003       0.003
heartRate       -7.058e-05      0.001     -0.134      0.894      -0.001       0.001
glucose             0.0009      0.000      2.936      0.003       0.000       0.001
===================================================================================

In [234]:
# prevalentStroke. If we increase it by 1, probability of TenYearCHD is increasing by 0.1578.

In [235]:
# 20) Use loglr model to predict Y in the train test and call it y_hat

In [236]:
y_hat = loglr.predict(x_train_c)

In [237]:
x_test_c = sm.add_constant(x_test)
y_hat_t = loglr.predict(x_test_c)

In [238]:
# 21) Transform y_hat to binary variable and call it y_hat_b

In [239]:
y_hat_b = (y_hat>0.5).astype(int)
y_hat_t_b = (y_hat_t>0.5).astype(int)

In [240]:
# 22) Write the first 5 values of y_hat_b

In [241]:
y_hat_b.head()

431     0
1041    0
1798    0
2005    0
584     0
dtype: int64

In [242]:
y_hat_t_b.head()

1522    0
3428    0
245     0
1049    0
2287    0
dtype: int64

In [243]:
# 23) Print the coefficient matrix and comment on it

In [244]:
print(confusion_matrix(y_train, y_hat_b))

[[2519   12]
 [ 401   34]]

In [245]:
# T: True, F: False, P: Positive, N: Negative
# 2519(TP)  12(FN)
# 401(FP)   34(TN)

In [246]:
print(confusion_matrix(y_test, y_hat_t_b))

[[1055    8]
 [ 190   19]]

In [247]:
# 1055(TP)  8(FN)
# 190(FP)   19(TN)

In [248]:
# 24) Calculate the accuracy of the logistic regression

In [249]:
accuracy = (2519+34)/(2519+12+401+34)
print(accuracy)

0.8607552258934592

In [250]:
accuracy_t = (1055+19)/(1055+8+190+19)
print(accuracy_t)

0.8443396226415094

In [251]:
# 25) Let X2 be the siginificance variables of the logistic regression

In [252]:
X2 = X.drop(['education', 'currentSmoker', 'BPMeds', 'prevalentHyp', 'diabetes', 'totChol', 'diaBP', 'BMI', 'heartRate'], axis = 1)

In [253]:
# 26) Write the first 10 rows of X2

In [254]:
X2.head(10)

   male  age  cigsPerDay  prevalentStroke  sysBP  glucose
0     1   39         0.0                0  106.0     77.0
1     0   46         0.0                0  121.0     76.0
2     1   48        20.0                0  127.5     70.0
3     0   61        30.0                0  150.0    103.0
4     0   46        23.0                0  130.0     85.0
5     0   43         0.0                0  180.0     99.0
6     0   63         0.0                0  138.0     85.0
7     0   45        20.0                0  100.0     78.0
8     1   52         0.0                0  141.5     79.0
9     1   43        30.0                0  162.0     88.0

In [255]:
# 27) Divide your data set into test and train sets using X2. Test set should contain %30 of the data set. Use random state as 123

In [256]:
x2_train, x2_test = train_test_split(X2, test_size = 0.3, random_state = 123)

In [257]:
# 28) Add constant to X2_train and call it X2_train_c

In [258]:
x2_train_c = sm.add_constant(x2_train)

In [259]:
# 29) Fit the logistic regression and call it loglr2

In [260]:
loglr2 = sm.Logit(y_train, x2_train_c).fit()

Optimization terminated successfully.
         Current function value: 0.371358
         Iterations 7

In [261]:
#30) Print the summary of the logistic regression

In [262]:
print(loglr2.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:             TenYearCHD   No. Observations:                 2966
Model:                          Logit   Df Residuals:                     2959
Method:                           MLE   Df Model:                            6
Date:                Wed, 03 Dec 2025   Pseudo R-squ.:                  0.1092
Time:                        07:46:37   Log-Likelihood:                -1101.4
converged:                       True   LL-Null:                       -1236.5
Covariance Type:            nonrobust   LLR p-value:                 2.160e-55
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              -8.5778      0.482    -17.806      0.000      -9.522      -7.634
male                0.4744      0.118      4.015      0.000       0.243       0.706
age                 0.0682      0.007      9.390      0.000       0.054       0.082
cigsPerDay          0.0244      0.005      5.348      0.000       0.015       0.033
prevalentStroke     1.4953      0.549      2.725      0.006       0.420       2.571
sysBP               0.0149      0.002      6.077      0.000       0.010       0.020
glucose             0.0094      0.002      4.732      0.000       0.006       0.013
===================================================================================

In [263]:
#31) Write which coefficients are statistically non-significant

In [264]:
# none of them

In [265]:
# 32)Use loglr2 model to predict Y in the train test and call it y2_hat

In [266]:
y2_hat = loglr2.predict(x2_train_c)

In [267]:
x2_test_c = sm.add_constant(x2_test)
y2_hat_t = loglr2.predict(x2_test_c)

In [268]:
# 33) Transform y2_hat to binary variable and call it y2_hat_b

In [269]:
y2_hat_b = (y2_hat>0.5).astype(int)
y2_hat_t_b = (y2_hat_t>0.5).astype(int)

In [270]:
# 34) Print the coefficient matrix and comment on it

In [271]:
print(confusion_matrix(y_train, y2_hat_b))

[[2515   16]
 [ 401   34]]

In [272]:
print(confusion_matrix(y_test, y2_hat_t_b))

[[1054    9]
 [ 190   19]]

In [273]:
# 35) Calculate the accuracy of the second logistic regression

In [274]:
accuracy_x2 = (2515+34)/(2515+16+401+34)
print(accuracy_x2)

0.8594066082265678

In [275]:
accuracy_x2_t = (1054+9)/(1054+9+190+19)
print(accuracy_x2_t)

0.835691823899371

In [276]:
# 36) Choose a machine learning we have used so far for classification model of your choice from sklearn library and apply it to the same data set (X2_train_c,X2_test) and compare the accuracy with the logistic regression models.

In [277]:
from sklearn import svm

In [278]:
svc = svm.SVC(kernel = 'linear', C=10)

In [279]:
svc.fit(x2_train, y_train)

SVC(C=10, kernel='linear')

In [280]:
y_pred = svc.predict(x2_test)

In [281]:
accuracy_score(y_test, y_pred)

0.8333333333333334

In [282]:
# accuracy with krenel='linear' and C=10 is 0.8333333333333334 which is slightly worse than logistic regression we did.
# Other SVM algorithms might give better result than ours.
# 0.835691823899371 > 0.8333333333333334